openapi: 3.0.3
servers:
  - url: http://ycla.local
info:
  title: YCLA-test
  version: 1.0.11
paths:
  /api/register:
    post:
      summary: ''
      description: ''
      operationId: ''
      requestBody:
        description: Register
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - patronymic
                - family
                - phone
                - email
                - password
                - password_confirmation
              properties:
                name:
                  type: string
                  example: Иван
                patronymic:
                  type: string
                  example: Иванович
                family:
                  type: string
                  example: Белов
                phone:
                  type: string
                  example: '+79161234567'
                email:
                  type: string
                  example: ivan@belyu.ru
                password:
                  type: string
                  example: asdf&5gH
                password_confirmation:
                  type: string
                  example: asdf&5gH
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              schema:
                type: object
  /api/login:
    post:
      summary: ''
      description: ''
      operationId: ''
      requestBody:
        description: Log in
        content:
          application/json:
            schema:
              type: object
              required:
                - email | phone
                - password
              properties:
                email:
                  type: string
                  default: ''
                phone:
                  type: string
                  default: ''
                password:
                  type: string
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              schema:
                type: object
                
  /api/products:
    get:
      summary: ''
      description: ''
      operationId: ''
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          description: Current page
          schema:
            type: integer
            example: 1
        - in: query
          name: name
          description: Filter
          schema:
            type: string
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              schema:
                type: object
                
          
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
